Repository GMC-Modding-Team/Community-Mod-Compilation-redux, pull requests merged in 2021-02, with the labels that each got.

#14 Update README.md
  README.md
Labels: GitHub

#16 [Experimental] Fixed Community aftershock
  data/Mainline_mods/Mods/Aftershock/vehicles/vehicle_overrides.json
Labels: Experimental F, Legacy update, bug, code removal, lint update

#15 [Experimental] broken mods
  .gitignore
  .typo-ci.yml
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/Flags.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/README.md
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/construction/afs_construction.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/furniture/afs_furniture.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/groups/afs_item_groups.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/groups/afs_monster_groups.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/groups/afs_vehicle_groups.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/groups/contruction_groups.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_armor.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_books.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_cbms.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_comestibles.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_item_overrides.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_items.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_materials.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_tools.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/afs_weapons.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/items/magazines.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/mapgen/afs_lab_vehicle_track.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/mapgen/afs_lab_weapons_range.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/modinfo.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/monsters/afs_zombies.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/other/afs_bionics.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/other/afs_mutations.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/other/afs_professions.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/other/afs_techniques.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/recipes/afs__recipes.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/recipes/afs_armor_recipes.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/recipes/afs_bionic_recipes.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/recipes/afs_comestible_recipes.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/recipes/afs_recipe_overrides.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/recipes/afs_requirements.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/recipes/afs_uncraft.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/vehicles/afs_vehicle_overrides.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/vehicles/afs_vehicle_parts.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock_master/vehicles/afs_vehicles.json
Labels: Experimental F, Legacy update, bug, code removal, enhancement, lint update

#20 [Experimental] documents fix
  documents/Updating_Legacy_JSON.md
Labels: documentation

#22 [GitHub] Update README.md
  README.md
Labels: GitHub

#19 [Experimental] working mods
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_vehicles.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/Flags.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/README.md
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/construction/afs_construction.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/furniture/afs_furniture.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/groups/afs_item_groups.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/groups/afs_monster_groups.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/groups/afs_vehicle_groups.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/groups/contruction_groups.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_armor.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_books.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_cbms.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_comestibles.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_item_overrides.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_items.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_materials.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_tools.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/afs_weapons.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/items/magazines.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/mapgen/afs_lab_vehicle_track.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/mapgen/afs_lab_weapons_range.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/modinfo.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/monsters/afs_zombies.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/other/afs_bionics.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/other/afs_mutations.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/other/afs_professions.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/other/afs_techniques.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/recipes/afs__recipes.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/recipes/afs_armor_recipes.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/recipes/afs_bionic_recipes.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/recipes/afs_comestible_recipes.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/recipes/afs_recipe_overrides.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/recipes/afs_requirements.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/recipes/afs_uncraft.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/vehicles/afs_vehicle_overrides.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/vehicles/afs_vehicle_parts.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/vehicles/afs_vehicles.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/laser_items.json
Labels: Experimental F, Legacy update, added content, bug, code removal, lint update

#24 [GitHub] Update README.md
  README.md
Labels: documentation

#26 [GitHub] Update .gitattributes
  .gitattributes
Labels: documentation

#28 [GitHub] update readme with estimate of mods
  README.md
Labels: documentation

#17 [Experimental] legacy mods
  data/Legacy_mods/mods/Animatronics/Faction.json
  data/Legacy_mods/mods/Tanks/vehicles.json
  data/Legacy_mods/mods/bio_mod/items/medicine.json
  data/Legacy_mods/mods/bio_mod/monsters/monster_drops.json
  data/Legacy_mods/mods/bio_mod/recipies/bionics.json
  data/Legacy_mods/mods/blazemod/items/guns/blob_turret.json
  data/broken_mods/FictonalWeapons/fic_item_groups.json
  data/broken_mods/FictonalWeapons/fic_mods.json
  data/broken_mods/FictonalWeapons/fic_recipes.json
  data/broken_mods/FictonalWeapons/fic_weapons.json
  data/broken_mods/FictonalWeapons/ficmags.json
  data/broken_mods/FictonalWeapons/modinfo.json
  data/broken_mods/FictonalWeapons/snippets.json
Labels: Experimental F, added content, bug, code removal

#29 [GitHub] add .reg keys for .md & .json
  tools/Registry/json.reg
  tools/Registry/markdown.reg
Labels: GitHub

#30 [Workflow] Check_Markdown_links.yml
  .github/workflows/Check_Markdown_links.yml
Labels: GitHub

#21 [Experimental] mainline mods
  data/Mainline_mods/Mods/Aftershock/items/gun/laser.json
  data/Mainline_mods/Mods/Aftershock/items/gun/plasma.json
  data/Mainline_mods/Mods/Aftershock/items/weapons.json
Labels: Experimental F, Legacy update, added content, bug, code removal, lint update

#18 [Experimental] maintained mods
  data/Maintained_mods/mods/Arcana/items/ranged.json
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Items/weapons.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Items/weapons.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Items/weapons.json
  data/Maintained_mods/mods/Nocts_cata_mod/Monsters/c_ranged_monster.json
Labels: Experimental F, Legacy update, added content, bug, lint update

#31 [Experimental] sub-category fixes
  data/Unleash_The_Mods/Working_mods/Large_Capacity_Storage_CBMs/bionics.json
  data/Unleash_The_Mods/Working_mods/Large_Capacity_Storage_CBMs/modinfo.json
  data/Unleash_The_Mods/Working_mods/Large_Capacity_Storage_CBMs/recipes.json
  data/Unleash_The_Mods/mods/Engineering_Essentials/recipes.json
  data/Unleash_The_Mods/mods/Engineering_Essentials/recipes/other.json
Labels: Experimental F, bug

#33 [Experimental] update autolearn
  .typo-ci.yml
  data/Unleash_The_Mods/mods/Engineering_Essentials/recipes/chems.json
  data/Unleash_The_Mods/mods/Lighting_Ammo/recipe.json
  data/broken_mods/Standalone_Salvaged_Robots/recipe_SR.json
Labels: Experimental F, bug

#34 [Experimental] Engineering essentials fixes
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/TODO.md
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/ammo.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/armor.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/books.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/chemicals.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/gunmod.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/itemgroups.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/items.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/modinfo.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/recipes.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/recipes/ammo.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/recipes/armor.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/recipes/chems.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/recipes/gunmod.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/recipes/materials.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/recipes/other.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/recipes/tools.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/requirements.json
  data/Unleash_The_Mods/Working_mods/Engineering_Essentials/vehicles.json
Labels: Experimental F, bug

#35 [GitHub] add json formatter
  .gitignore
  tools/format/json_formatter.exe
Labels: GitHub

#37 [Documentation] Create VS_linter.md
  .typo-ci.yml
  documents/Installation_Times_for_Gun_Mods.md
  documents/Learning_Code.md
  documents/Links/CDDA-Documents.url
  documents/Links/CDDA-Item Browser.url
  documents/Links/CDDA-JSON Linting Tool.url
  documents/Links/GMC-Documents-online.url
  documents/Links/GMC-Documents.url
  documents/VS_linter.md
Labels: Experimental F, documentation

#36 [Experimental] m.a.g armory update
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/itemgroups/ammo.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/itemgroups/guns.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/itemgroups/magazines.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/items/ammo/50AE.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/items/ammo_types.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/items/generic/casing.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/items/gun/50AE.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/items/magazine/50AE.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/items/melee/swords_and_blades.json
  data/Unleash_The_Mods/Working_mods/M_A_G_Armory/modinfo.json
Labels: Experimental F, bug

#38 [Experimental] modinfo fixes
  .typo-ci.yml
  data/Unleash_The_Mods/mods/Abrahms_Martial_Arts/modinfo.json
  data/Unleash_The_Mods/mods/Advanced_Technologies/modinfo.json
  data/Unleash_The_Mods/mods/Agent_Bandits/modinfo.json
  data/Unleash_The_Mods/mods/Airdrops_and_Alchemy/modinfo.json
  data/Unleash_The_Mods/mods/Anti_Fungal_Towers/modinfo.json
  data/Unleash_The_Mods/mods/Artyom_Emporium/modinfo.json
  data/Unleash_The_Mods/mods/Crystallized_mutations/modinfo.json
  data/Unleash_The_Mods/mods/Custom_Bandit_King_Start/modinfo.json
  data/Unleash_The_Mods/mods/Drug_effects/modinfo.json
  data/Unleash_The_Mods/mods/EvilMoose/modinfo.json
  data/Unleash_The_Mods/mods/Fantasy/modinfo.json
  data/Unleash_The_Mods/mods/Fantasy_realm_scenarios/modinfo.json
  data/Unleash_The_Mods/mods/Jury_Rigged_Robots/modinfo.json
  data/Unleash_The_Mods/mods/Machine/modinfo.json
  data/Unleash_The_Mods/mods/Merchant/modinfo.json
  data/Unleash_The_Mods/mods/More_Survivor_Stuff/modinfo.json
  data/Unleash_The_Mods/mods/Nimian_Manufacture/modinfo.json
  data/Unleash_The_Mods/mods/Pneumatic_fun/modinfo.json
  data/Unleash_The_Mods/mods/Project_Kawaii/modinfo.json
  data/Unleash_The_Mods/mods/Realistic_bows/modinfo.json
  data/Unleash_The_Mods/mods/Reds_Odd_Additions/modinfo.json
  data/Unleash_The_Mods/mods/Sarcophagi_Access/modinfo.json
  data/Unleash_The_Mods/mods/Scaly_duds/modinfo.json
  data/Unleash_The_Mods/mods/Science_Additions/modinfo.json
  data/Unleash_The_Mods/mods/Sunken_Bridges/modinfo.json
  data/Unleash_The_Mods/mods/Sunken_Bridges/modinfo.txt
  data/Unleash_The_Mods/mods/Terrain_BASEMOD/modinfo.json
  data/Unleash_The_Mods/mods/Uekibati_mod/modinfo.json
  data/Unleash_The_Mods/mods/Waxed_Clothes/modinfo.json
  data/Unleash_The_Mods/mods/Weaker_turrets/modinfo.json
  data/Unleash_The_Mods/mods/Whaleys_Collectibles/modinfo.json
  data/Unleash_The_Mods/mods/Whaleys_New_Hair_Mod/modinfo.json
  data/Unleash_The_Mods/mods/Wrecks/modinfo.json
  data/Unleash_The_Mods/mods/XEAS/modinfo.json
  data/Unleash_The_Mods/mods/XProfessions/modinfo.json
  data/Unleash_The_Mods/mods/ZSFixed_Extended_Buildings/modinfo.json
  data/Unleash_The_Mods/mods/cursed_thighs/modinfo.json
  data/Unleash_The_Mods/mods/metal_elemental/modinfo.json
  data/Unleash_The_Mods/mods/miso_Touhou/modinfo.json
  data/Unleash_The_Mods/mods/miso_Touyou/modinfo.json
  data/Unleash_The_Mods/mods/pixels_fuckery/modinfo.json
  data/Unleash_The_Mods/mods/xtal/modinfo.json
Labels: Compatibility, Experimental F, added content

#41 [Documentation] Abstract can be used on recipes
  documents/Updating_Legacy_JSON.md
Labels: documentation

#42 [Experimental] food preservaion by irradion update
  data/Unleash_The_Mods/Working_mods/Food_Preservation_by_Irradiation/README.md
  data/Unleash_The_Mods/Working_mods/Food_Preservation_by_Irradiation/Tools.json
  data/Unleash_The_Mods/Working_mods/Food_Preservation_by_Irradiation/modinfo.json
  data/Unleash_The_Mods/Working_mods/Food_Preservation_by_Irradiation/recipes_a_single_stock.json
  data/Unleash_The_Mods/Working_mods/Food_Preservation_by_Irradiation/recipes_b_batch_in_a_bag_stock.json
  data/Unleash_The_Mods/Working_mods/Food_Preservation_by_Irradiation/rigs.json
  data/Unleash_The_Mods/Working_mods/Food_Preservation_by_Irradiation/vehicle_parts.json
Labels: Experimental F, bug

#40 [Experimental] uekibati update
  data/Unleash_The_Mods/Working_mods/Uekibati_mod/melee.json
  data/Unleash_The_Mods/Working_mods/Uekibati_mod/modinfo.json
  data/Unleash_The_Mods/Working_mods/Uekibati_mod/recipe_others.json
Labels: Experimental F, bug, code removal

#43 [Experimental] fern mod update
  data/Unleash_The_Mods/mods/fern_mod/forest.json
  data/Unleash_The_Mods/mods/fern_mod/items.json
Labels: Experimental F, bug

#44 [Experimental] Gormands graces update
  data/Unleash_The_Mods/mods/Gourmands_Graces/containers.json
Labels: Experimental F, bug, code removal

#39 [Experimental] remove unwanted files
  data/Unleash_The_Mods/mods/Advanced_Technologies/preload.lua
  data/Unleash_The_Mods/mods/Project_Kawaii/ReadMe.txt
Labels: Experimental F, code removal

#45 [Experimental] Fix hdroof
  data/Legacy_mods/mods/Salvaged_Robots/robot_additions/vehicles.json
  data/Legacy_mods/mods/Tanks/vehicles.json
  data/Mainline_mods/Mods/Aftershock/vehicles/vehicle_overrides.json
  data/Mainline_mods/Mods/Aftershock/vehicles/vehicles.json
  data/Maintained_mods/mods/No_Hope_Night_Pryanik/vehicles.json
  data/Maintained_mods/mods/Nocts_cata_mod/Vehicles/c_vehicles.json
  data/Maintained_mods/mods/Tankmod_Revived/vehicles.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/vehicles/modified.json
  data/Maintained_mods/mods/expansion_tefnut/vehicles/modified.json
  data/Unleash_The_Mods/Working_mods/Community_Aftershock/vehicles/afs_vehicle_overrides.json
  data/Unleash_The_Mods/mods/Advanced_Technologies/at_vehicles.json
  data/Unleash_The_Mods/mods/Fallout/vehicle_gunrunner/gunrunners.json
  data/Unleash_The_Mods/mods/Ninja_mod/ninja_vehicle.json
  data/Unleash_The_Mods/mods/PKs_Rebalancing/vehicle/pk_vehicle_bfg.json
  data/broken_mods/Standalone_Salvaged_Robots/robot_additions/vehicles.json
Labels: Experimental F, bug

#51 [Github] .gitattributes update
  .gitattributes
Labels: GitHub

#54 [Tools] Add catatilesetstudio
  tools/CDDATilesetStudioV0.10/CataTilesetStudio.exe
  tools/CDDATilesetStudioV0.10/CataTilesetStudio.exe.config
  tools/CDDATilesetStudioV0.10/Microsoft.WindowsAPICodePack.Shell.dll
  tools/CDDATilesetStudioV0.10/Microsoft.WindowsAPICodePack.dll
  tools/CDDATilesetStudioV0.10/Newtonsoft.Json.dll
  tools/CDDATilesetStudioV0.10/SystemTiles.json
  tools/CDDATilesetStudioV0.10/readme.txt
Labels: GitHub

#49 [Experimental] Update blazemod W.I.P
  .typo-ci.yml
  data/Legacy_mods/mods/blazemod/blaze_construction.json
  data/Legacy_mods/mods/blazemod/blaze_furniture.json
  data/Legacy_mods/mods/blazemod/construction_group.json
  data/Legacy_mods/mods/blazemod/items/guns/blaze_weapons.json
  data/Legacy_mods/mods/blazemod/items/guns/blob_turret.json
  data/Legacy_mods/mods/blazemod/items/vehicle/blaze_other.json
  data/Legacy_mods/mods/blazemod/recipes/blaze_weapons_recipes.json
  data/Legacy_mods/mods/blazemod/vehicleparts/blaze_other_parts.json
  data/Legacy_mods/mods/blazemod/vehicleparts/blaze_weapons_parts.json
  data/Legacy_mods/mods/blazemod/vehicleparts/diamond_turret.json
  data/Legacy_mods/mods/blazemod/vehicleparts/vortex_turret.json
Labels: Experimental F, added content, bug

#3 [Experimental] add tileset for xotto cosmetics
  .typo-ci.yml
  .vs/Community-Mod-Compilation-redux/v16/.suo
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/expan.png
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/expan2.png
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/fallback.png
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/mod_tileset.json
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/modinfo.json
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/tiles.png
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/tileset.txt
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/tree.png
  data/Unleash_The_Mods/mods/Tilset_XottoCosmetics/treeO.png
Labels: Experimental F, added content, tileset
